### ISSUE TITLE
FunctionTransformer raises FutureWarning

### ISSUE THREAD

**Issue by joaopfonseca** [AlgoWit/research-learn#2]
Current default on `FunctionTransformer()` function (`rlearn/utils/validation.py` script, line 86) raises a `FutureWarning`, which can be fixed by setting its current default value `FunctionTransformer(validate=True)`, which is what the code is already doing at the moment anyway.

Should I open a PR to fix this?

**Comment by georgedouzas** [comment]
Yes please.
