### ISSUE TITLE
ModelSearchCV does not accept different fit_params for different models

### ISSUE THREAD

**Issue by joaopfonseca** [AlgoWit/research-learn#3]
Although it's something uncommon to use, in some occasions I needed to test different models that had varying `fit_params`. The current version of `ModelSearchCV` does not accept them. Editing the class `MultiEstimatorMixin` (script `rlearn/model_selection/search.py`) by adding a simple check fit params part in the code fixes this problem.

Should I prepare an example to show this behavior?

**Comment by georgedouzas** [comment]
Yes please, provide here an example that does not have the expected behaviour.

**Comment by joaopfonseca** [comment]
I was trying to replicate the error in a simple example, but apparently now it's working, may have been a problem from my code instead. I suppose this issue can be closed. If it comes up again I'll reopen the issue.
